apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-app

resources:
- namespace.yaml
- configmap.yaml
- deployment.yaml
- ingress.yaml

commonLabels:
  app: todo-app
  version: v1

images:
- name: gcr.io/rd-sre-assessment-center/todo-app
  newTag: latest 