apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-todo-app-config
  namespace: spring-boot-todo
  labels:
    app: spring-boot-todo-app
data:
  application-kubernetes.properties: |
    # Spring Boot Todo App Configuration for Kubernetes
    server.port=8080
    
    # H2 Database Configuration
    spring.datasource.url=jdbc:h2:mem:tododb
    spring.datasource.driverClassName=org.h2.Driver
    spring.datasource.username=sa
    spring.datasource.password=
    
    # JPA/Hibernate Configuration
    spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
    spring.jpa.hibernate.ddl-auto=create-drop
    spring.jpa.show-sql=false
    spring.jpa.properties.hibernate.format_sql=false
    
    # H2 Console (disable in production)
    spring.h2.console.enabled=false
    
    # Actuator Configuration
    management.endpoints.web.exposure.include=health,info,metrics,prometheus
    management.endpoint.health.show-details=when_authorized
    management.endpoint.health.probes.enabled=true
    
    # Logging Configuration
    logging.level.com.example.todo=INFO
    logging.level.org.springframework.web=INFO
